name: CI/CD Pipeline - App1

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql db: digital_mortgage
        postgresql user: ${{ secrets.POSTGRES_USERNAME }}
        postgresql password: ${{ secrets.POSTGRES_PASSWORD }}
        
    - name: Build with Maven
      env: 
        PORT: 8181
        POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      run: mvn clean install

    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6.2
      with:
        image: gemardyz/digital-mortgage-service:main-latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Deploy to DigitalOcean - App1
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
        command: apps create --spec /opt/digitalocean/digital-mortgage-deployment/docker-compose.yml


