name: CI/CD Pipeline - App1

on:
  push:
    branches: ["main"]
env:
  IMG_NAME: gemardyz/digital-mortgage-service
  REGISTRY: docker.io
  GITHUB_SHA: ${{github.sha}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql db: digital_mortgage
        postgresql user: ${{ secrets.POSTGRES_USERNAME }}
        postgresql password: ${{ secrets.POSTGRES_PASSWORD }}
        
    - name: Build with Maven
      env: 
        PORT: 8181
        POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      run: mvn clean install

    - name: Debug
      run: | 
        echo "github.ref -> {{ github.ref }}"
          
    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMG_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
          
    - name: Build and Push Docker image
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Deploy to DigitalOcean - App1
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
        command: apps create --spec /opt/digitalocean/digital-mortgage-deployment/docker/docker-compose.yml
  deploy:
      runs-on: ubuntu-latest
      needs: [build]

      steps:
        - name: Configure SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
        - name: SSH to Server
          run: |
            ssh -i ${{ secrets.DIGITALOCEAN_SSHKEY }} ${{secrets.DIGITALOCEAN_USERNAME}}@${{secrets.DIGITALOCEAN_HOST}} 'cd /opt/digitalocean/'
            
# deploy:
#       runs-on: ubuntu-latest
#       needs: build

#       steps:
#         - name: Deploy to Digital Ocean droplet via SSH action
#           uses: appleboy/ssh-action@v0.1.3
#           with:
#             host: ${{ secrets.DIGITALOCEAN_HOST }}
#             username: ${{ secrets.DIGITALOCEAN_USERNAME }}
#             key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
#             envs: IMAGE_NAME,REGISTRY,{{ secrets.DIGITALOCEAN_TOKEN }},GITHUB_SHA
#             script: |
#               # Login to registry
#               docker login -u ${{ secrets.DIGITALOCEAN_TOKEN }} -p ${{ secrets.DIGITALOCEAN_TOKEN }} docker.io
#               # Stop running container
#               docker stop $(echo $IMAGE_NAME)
#               # Remove old container
#               docker rm $(echo $IMAGE_NAME)
#               # Run a new container from a new image
#               docker run -d \
#               --restart always \
#               --name $(echo $IMAGE_NAME) \
#               $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
